version: '3'
services:
# ngnix server
# terminates SSL and set cert's CN into the header
# It could be configured to pass the whole cert as a PEM in the header
  nginx: 
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    ports:
      - 80:80
      - 443:443

# js express server
  helloworld:
    build: 
      context: ./
      dockerfile: express/Dockerfile
    ports:
      - 8080:8080

# jdk11 springboot server
  springboot:
    build: 
      context: ./
      dockerfile: springboot/Dockerfile
    ports:
      - 9090:9090